# Generated by Django 3.2.6 on 2022-07-04 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.collection'),
            preserve_default=False,
        ),
    ]
