# Generated by Django 3.2.6 on 2022-07-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderproduct_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
