# Generated by Django 3.2.6 on 2022-07-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderproduct_at_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='at_ordered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
