# Generated by Django 3.2.6 on 2022-07-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220712_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='items', to='store.OrderItem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
