# Generated by Django 3.2.6 on 2022-08-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='shop_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
