# Generated by Django 3.2.6 on 2022-08-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staff_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
